# docker-compose.yml - Located in the root of your project: high-concurrency-booking-system/
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: booking_mongodb
    ports:
      - "27017:27017" # Map local 27017 to container 27017
    volumes:
      - mongo_data:/data/db # Persist MongoDB data
    networks:
      - booking-network

  redis:
    image: redis:latest
    container_name: booking_redis
    ports:
      - "6379:6379" # Map local 6379 to container 6379
    networks:
      - booking-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: booking_rabbitmq
    ports:
      - "5672:5672" # Map local 5672 to container 5672 (for app connection)
      - "15672:15672" # Map local 15672 to container 15672 (for web UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - booking-network

volumes:
  mongo_data: # Define the named volume for MongoDB data persistence

networks:
  booking-network:
    driver: bridge # Create a custom network for these services