version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - booking_network

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - booking_network

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - booking_network
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

networks:
  booking_network:
    driver: bridge

volumes:
  postgres_data: